/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Note {
  id: string
  title: string
  createdAt: number
  icon?: string
}
export interface Block {
  id: string
  noteId: string
  blockType: string
  content: string
  position: number
}
export declare class NotesDb {
  constructor(path: string)
  addNote(title: string, icon?: string | undefined | null): string
  getNotes(): Array<Note>
  getNote(id: string): Note
  updateNoteTitle(noteId: string, title: string): void
  addBlock(noteId: string, blockType: string, content: string): string
  updateBlock(blockId: string, content: string): void
  getBlocks(noteId: string): Array<Block>
}
